url: https://dataportal.slh.wisc.edu
baseurl:

# Site settings
title: Wisconsin State Laboratory of Hygiene DataPortal
organization: Wisconsin State Laboratory of Hygiene
logo: wslh-logo.png
logo_alt: Wisconsin State Laboratory of Hygiene DataPortal
email: 
description: "The Wisconsin State Laboratory of Hygiene (WSLH) is the state's public and environmental health laboratory. As part of the University of Wisconsin-Madison, the WSLH is committed to exploring new ideas which benefit the state, the nation and the world."

# Google Analytics
google_tag: 'GTM-MGJB9P5'

collections:
  dashboards:
    output: true
    permalink: /:slug
    sort_by: dashboard-id

supporters:
  - name: AWS Diagnostic Development Initiative (DDI)
    tag_line:
    logo: AWS-DDI.png
    address: https://aws.amazon.com/government-education/nonprofits/disaster-response/diagnostic-dev-initiative/
  
  - name: CDC ELC Cooperative Agreement
    tag_line: Epidemiology and Laboratory Capacity for Prevention and Control of Emerging Infectious Diseases
    logo: 
    address: https://www.cdc.gov/ncezid/dpei/epidemiology-laboratory-capacity.html

# Social networks
social:
  - title: github
    url: https://github.com/wslh-data


# Postal address (add as many lines as necessary)
address:
  - line: 'Attn: Customer Service'
  - line: Wisconsin State Laboratory of Hygiene
  - line: 2601 Agriculture Drive, PO Box 7996
  - line: Madison, WI 53707-7996

# Build settings
markdown: kramdown
permalink: pretty